on: [push]
jobs:
  print-content:
    runs-on: docker
    container:
      image: rust:slim
    steps:
      - name: install action dependencies
        run: apt install --no-install-recommends --update -y nodejs just
      - name: setup toolchain
        run: |
          rustup component add rustfmt clippy llvm-tools-preview
          cargo install cargo-llvm-cov --locked

      - name: checkout code
        uses: actions/checkout@v6

      - name: build
        run: just build

      - name: format
        run: just format-assess
      - name: lint
        run: just lint-assess
      - name: check
        run: just check-assess
      - name: test
        run: just test-assess
      - name: coverage
        run: just cover-assess

