on:
  push:
    branches:
      - '*'
    paths:
      - src/**
      - static/*
      - .forgejo/**
      - .justfile
      - Cargo.*

jobs:
  verify:
    runs-on: docker
    timeout-minutes: 20
    container:
      image: rust:slim
    steps:
      - name: Set up action dependencies
        run: |
          apt-get install --no-install-recommends --update -y nodejs git nix
          echo experimental-features = nix-command flakes >> /etc/nix/nix.conf
          nix profile install nixpkgs#just # trixie is on nix 2.26

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-tags: true

      - name: Cleanup checkout action dependencies
        run: apt-get purge -y nodejs git

      - name: Set up CI user
        run: useradd -m ci && chown -R ci /nix .

      - name: Set up Rust toolchain
        run: |
          rust_version=$(grep '^rust-version' Cargo.toml | cut -d \" -f 2)

          su ci -c "
            rustup default '$rust_version'
            rustup toolchain install nightly
            rustup component add llvm-tools
            rustup component add --toolchain nightly rustfmt clippy
            rustup target add \
              x86_64-unknown-linux-musl \
              x86_64-unknown-linux-gnu
          "

      - name: Assess
        run: /root/.nix-profile/bin/just ci-nix "$PATH" verify
