FROM alpine:3.24 as build
LABEL org.opencontainers.image.authors="Juno Takano <juno@jutty.dev>"
ENV REPO_URL=https://codeberg.org/jutty/en

# Setup tooling
RUN apk add curl git
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Fetch source
RUN <<EOF
    LAST_TAG=$(git ls-remote --tags "$REPO_URL" | grep refs/tags \
        | sed 's/.*refs\/tags\///' | sort -V | tail -n 1)
    git config --global advice.detachedHead false
    git clone --verbose -b "$LAST_TAG" --depth 1 \
        --single-branch --no-tags "$REPO_URL" /src
EOF

# Build
WORKDIR /src
RUN apk add gcc musl-dev
RUN /root/.cargo/bin/cargo build --locked --release

# Describe
RUN apk add file musl-utils
RUN <<EOF
    target/release/en --version
    echo sha256sum $(sha256sum target/release/en)
    file target/release/en
    ldd target/release/en
EOF

# Launch
FROM scratch
WORKDIR /root
COPY --from=build /src/target/release/en /usr/local/bin/en
EXPOSE 80/tcp
CMD [ "en", "-p", "80" ]
